version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: TestingThis0ut
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
        - "3306:3306"

  app:
    build:
      context: .
      dockerfile: tests/Dockerfile
    image: sqlsorcery_v2_tests
    environment:
      DB_DIALECT: mysql+pymysql
      DB: mysql
      DB_USER: root
      DB_PWD: TestingThis0ut
      DB_PORT: 3306
      DB_SCHEMA: mysql
      DB_SERVER: mysql
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOSTS_CONNECT_TIMEOUT: 30
    command: sh -c "/wait && pipenv run pytest -s -v"
    depends_on:
      - mysql