version: "3"
services:
  app:
    build:
      context: .
      dockerfile: tests/Dockerfile
    image: sqlsorcery_v2_tests
    environment:
      DB_DIALECT: sqlite
      DB: test.db
    command: pipenv run pytest -s -v